apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: #broker_name#-steward-cf
  namespace: steward
  labels:
    app: #broker_name#-steward-cf
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: #broker_name#-steward-cf
    spec:
      containers:
      - name: #broker_name#-steward-cf
        image: #deploy_image#
        imagePullPolicy: Always
        env:
        - name: BROKER_NAME
          value: #broker_name#
        - name: LOG_LEVEL
          value: trace
        - name: WATCH_NAMESPACES
          value: default
        - name: BROKER_ACCESS_SCHEME
          value: "#broker_access_scheme#"
        - name: BROKER_HOST
          value: "#broker_host#"
        - name: BROKER_PORT
          value: "#broker_port#"
        - name: BROKER_USERNAME
          value: "#broker_username#"
        - name: BROKER_PASSWORD
          value: "#broker_password#"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          failureThreshold: 1
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
---
apiVersion: v1
kind: Service
metadata:
  name: #broker_name#-steward-cf
  namespace: steward
  labels:
    app: #broker_name#-steward-cf
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: #broker_name#-steward-cf
